feat: Implement delete news article service layer - EXO-70383 - Meedsio/MIPs#119
Meeds-io/content pull request #18
Opened 2024-04-17 13:58 UTC by sofyenne

2024-04-18 17:30 UTC, azayati requested changes

2024-04-18 17:30 UTC, azayati commented on content-service/src/main/java/io/meeds/news/rest/NewsRestResourcesV1.java
> +      if (news == null || (newsObjectType != null && NewsUtils.isDeletedNews(news.getId(), newsObjectType, currentIdentity.getUserId()))) {
we can instead add isDeleted attribute for News model

2024-04-18 17:30 UTC, azayati commented on content-service/src/main/java/io/meeds/news/service/impl/NewsServiceImpl.java
> +      throw new IllegalAccessException("User " + currentIdentity.getUserId() + " is not authorized to delete news");
you can change also that for createNews and editNews cases, corresponding rest services to be tested for non authorized users

2024-04-19 11:54 UTC, sofyenne commented on content-service/src/main/java/io/meeds/news/rest/NewsRestResourcesV1.java
> +      if (news == null || (newsObjectType != null && NewsUtils.isDeletedNews(news.getId(), newsObjectType, currentIdentity.getUserId()))) {
done !

2024-04-19 13:37 UTC, azayati approved these changes
LGTM

2024-04-19 13:38 UTC, merged